### ISSUE TITLE
Shell编程极简入门实践.md  的一些改进建议

### ISSUE THREAD

**Issue by mzhboy** [StevenSLXie/Tutorials-for-Web-Developers#2]
3.数组
`declare -a NAMES=('Steven' 'Peter' 'David')`
bash限定

4.1 运算符还有`let`，`$((3+2*3))`
额外的还有bc

4.2 逻辑运算
`&&`，`||`，在bash,zsh,ash等是可用的，也是常用的

5\. for循环中，`for var in "$arg"`只会把`"$arg"`当作一个字符串，忽略里面的空白符(因为有双引号)。这是个陷阱。
一般用`for var in $arg`

7\. sed命令，
注明：一般是`sed 's/old/new/' file`这样用单引号而不是双引号，除非需要shell变量展开到sed命令中才用双引号。

**Comment by mzhboy** [comment]
起码zsh，ash不能用。ash是busybox的默认shell，用途很广

**Comment by StevenSLXie** [comment]
谢谢你~
已补充做了说明~
我把这个close了。
