### ISSUE TITLE
一处文字对应的问题

### ISSUE THREAD

**Issue by starlightme** [StevenSLXie/Tutorials-for-Web-Developers#3]
-o对应或逻辑，-a对应与逻辑，应该是这样的吧，原文中的对应关系按照前后顺序('分别')来看是错误的，希望能修正下~
>Shell编程里，与逻辑和或逻辑分别是用'-o'和'-a'来表示的

**Comment by StevenSLXie** [comment]
已改正。感谢~

**Comment by starlightme** [comment]
不客气，感谢你的教程w
